### ISSUE TITLE
Validators? Speed?

### ISSUE THREAD

**Issue by kokujin** [simpleviewinc/mongolayer#1]
1. Is there a list of validators somewhere(isEmail, isURL e.t.c)?
2. Can one set a model property as unique
3. Are there benchmarks?

**Comment by owenallenaz** [comment]
1. All of the validation is documented in the jsvalidator at https://github.com/simpleviewinc/jsvalidator library as we simply pass it off to that library to handle.

In general, the validation is for primitive validation such as string, number, float, date, object, array. At this time there isn't validation in place for things like checking an email or URL. If you need to do complex validation then it's recommended to use the hook system to pre-process items such as with a beforePut hook. If that doesn't work it's not out of bounds to update jsvalidator so that you could pass functions which would be run on validation.
1. Regarding model property as unique, if you are referring to a unique index constraint then yes. You do so by declaring `indexes` or running `addIndex` on your model before attaching it to a connection. See the docs for examples.
2. No benchmarks yet. In general, this is wrapper for node-mongodb-native, so mongolayer performance is their performance + a few ms per query.

**Comment by kokujin** [comment]
Thanks, I am not sure of how to declare unique indexes on fields though. Here is a snippet

```
var User = new mongolayer.Model({
    collection: "users",
    fields: [
        {
            name: "userid",
            validation: {
                type: "string"                                
            },
            required: true,
                         unique: true
        },  {
            name: "email",
            validation: {
                type: "string",
            },
            required: true,
                        unique: true                         
        }, {
            name: "nickname",
            validation: {
                type: "string"
            },
            required: true,
                        unique: true                          
        }, {
            name: "password",
            validation: {
                type: "string"
            },
            required: true
        }
    ],
    indexes: [{
        keys: {
            userid: "string",
                        emai": 'string',
                        nickname": 'string',
        }
    }],
    hooks: []
});

```
1. Do I declare the field both in the "fields" and "indexes" array?
2. Do I declare the unique as a separate attribute on the field or in its validation object property?
3. How do I declare the additional property sparse, as in "unique: true, sparse: true"?

It would be great if you could provide an example. Thanks

**Comment by owenallenaz** [comment]
The docs show an example at https://github.com/simpleviewinc/mongolayer#modeladdindexargs

Here's an example with your config cleaned up.

``` js
var User = new mongolayer.Model({
    collection: "users",
    fields: [
        {
            name: "userid",
            validation: {
                type: "string"
            },
            required: true
        }, {
            name: "email",
            validation: {
                type: "string",
            },
            required: true
        }, {
            name: "nickname",
            validation: {
                type: "string"
            },
            required: true
        }, {
            name: "password",
            validation: {
                type: "string"
            },
            required: true
        }
    ],
    indexes: [
        {
            keys: {
                userid: "string",
                email: 'string',
                nickname: 'string',
            },
            options : { unique : true }
        }
    ]
});
```

**Comment by owenallenaz** [comment]
Closing, been dead a while.
