### ISSUE TITLE
Hooks cannot be used with Aggregation

### ISSUE THREAD

**Issue by celalo** [simpleviewinc/mongolayer#4]
As far as I can see, hooks cannot be made use of when aggregate queries are run. Is there plan to support it?

**Comment by owenallenaz** [comment]
I am not opposed to doing hooks on aggregation. Do you have an example of how you want to use them? Are you looking to do relationship hooks to pull in related models that are normally on beforeFind/afterFind or custom hooks that are specific to aggregation. Aggregates can be a bit tricky because you can return data in almost any format, while a normal find() returns it in only one format (array of docs). If you just need specific hooks for aggregation that it would be pretty easy to add `beforeAggregate_[name]` and `afterAggregate_[name]`. It is also possible for us to castDocs. I know there have been times where I've wanted to do an aggregate to pull data but wanted to be able to use all of the tools I have available on a standard find. Theoretically if I exposed

```
aggregate(pipeline, { hooks : ["afterFind_relationship1", "afterAggregate_foo"], castDocs : true }, cb)
```

It would basically allow an aggregate to act almost exactly like `find()` but using the aggregate pathway for fulling the data.

**Comment by celalo** [comment]
I intend to use aggregation mainly to join collections with `$lookup` but I can not make use `afterFind` hooks because I need to filter data based on fields of the joined collection since `afterFind` is for post-processing the data collected via `find`. It's great for populating relationships but not as powerful as aggregation.

I agree aggregations can be tricky not only because you can return data in almost any format but also a demanding aggregation pipeline can be quite tangled. I am more into`beforeAggregate` type of hook. Maybe it would be relatively easy to come up with a hook that enables appending to the aggregation pipeline array. That way it would be possible to just define a `beforeAggregate` hook to make use of `$sort`, `$limit` and `$skip` to enable pagination on the aggregation query. Something like this:

```
model.addHook({

	name : "pagination",
	type : "beforeAggregate",
	handler : function(args, cb) {

		args.pipeline.push( { $limit : 20 } );
		args.pipeline.push( { $skip : 100 } );
		args.pipeline.push( { $sort : { timestamp: -1 } } );

		cb(null, args);
	},
	required : true
});
```

Actually, `sort`, `limit` and `skip` can be `Model.aggregate()` options like `Model.find()` options which can be added to the very end of pipeline array automatically. 

Furthermore, being able to append to the aggregation pipeline array could at least enable possibility to have simple common operations like choosing which fields to be returned using `$project`.

Last but not least, the best use case scenario in my case would be being able to append a `$match` operation to the pipeline so I can implement access control to the documents. For example, I could have just chained the following example operation with a `beforeAggregate` hook so I can enforce authorization rules.

```
{
   $match: {
      { "permittedUsers": { "$elemMatch": { "userId": (new mongolayer.ObjectId _id), "operation": "edit" } } }
   }
}
```

**Comment by owenallenaz** [comment]
We have pushed out this capability for beforeAggregate and afterAggregate. In addition to adding the ability for virtuals and docs to be casted on aggregation calls. Closing this down as complete.
